name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-site:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install AWS-CLI
        run: python -m pip install awscli

      - name: Deploy site.
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_ASSETS_BUCKET: ${{ secrets.S3_ASSETS_BUCKET }}
        run: |
          aws s3 sync $REPO_PATH/$DEPLOY_DIRECTORY s3://$S3_ASSETS_BUCKET \
          --exclude ".git*" --exclude "README" --delete --acl public-read
