name: deploy
on:
  push:
    branches:
      - master
jobs:
  aws-ec2-deploy:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }}
      REPO_NAME: "aboutme"
    steps:
      - name: Install SSH client and start ssh-agent.
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Deploy
        env:
          WEB_PATH: ${{ secrets.EC2_WEB_PATH }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          rsync -avP --delete --exclude=".git*" \
          --rsync-path="mkdir -p $WEB_PATH/$REPO_NAME && rsync" \
          -e "ssh -o StrictHostKeyChecking=no" \
          $REPO_PATH/. $USERNAME@$HOST:$WEB_PATH/$REPO_NAME

