name: deploy
on:
  push:
    branches:
      - master
    paths:
      - index.html
jobs:
  aws-ec2-deploy:
    runs-on: ubuntu-latest
    env:
      REPO_PATH: ${{ github.workspace }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Set repo name
        run: echo "::set-env name=REPO::$(echo $REPOSITORY | cut -d / -f 2)"

      - name: Install SSH client and start ssh-agent.
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_DEPLOY_KEY }}

      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Deploy
        env:
          WEB_PATH: ${{ secrets.AWS_EC2_WEB_PATH }}
          REMOTE: ${{ secrets.AWS_EC2_REMOTE }}
        run: |
          rsync --progress --recursive --delete \
          --exclude .git/ --exclude .github/ \
          --rsync-path="mkdir -p $WEB_PATH/$REPO_NAME && rsync" \
          $REPO_PATH/$REPO_NAME/. $REMOTE:$WEB_PATH/$REPO_NAME

