name: pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "index.html"
      - ".github/workflows/pages.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Copy 'index.html' file to 'public' directory.
        run: mkdir -p public && cp index.html public

      - name: Uploading artifacts.
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
